apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-worker
  name: locust-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - image: locustio/locust
        name: locust
        volumeMounts:
          - name: locustfile
            mountPath: /mnt/locust
        args:
          - --locustfile
          - {{ .Values.locustfile }}
          - --worker
          - --master-host=locust
        resources: {}
      volumes:
        - name: locustfile
          configMap:
            name: locustfile-config
status: {}
