apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      name: locust
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: locustio/locust
        volumeMounts:
          - name: locustfile
            mountPath: /mnt/locust
        args:
          - --locustfile
          - {{ .Values.locustfile }}
          - --master
          - --users
          - "{{ .Values.users }}"
          - --spawn-rate
          - "{{ .Values.hatchRate }}"
          - --headless
          - --run-time
          - {{ .Values.runTime }}

          - --host
      {{ if .Values.host }}
          - {{ .Values.host }}
      {{ else }}
        {{ if eq .Values.testCaseNumber 1}}
          - http://nginx.{{ .Values.namespace }}.svc.cluster.local
        {{ else }}
          - http://apiRule.{{ .Values.clusterDomain }}
        {{ end }}
      {{ end }}
        ports:
          - name: loc-master-web
            containerPort: 8089
            protocol: TCP
          - name: loc-master-p1
            containerPort: 5557
            protocol: TCP
      volumes:
        - name: locustfile
          configMap:
            name: locustfile-config
