apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    job-name: locust
  name: locust
  namespace: kyma-perf-tests
spec:
  ports:
  - port: 5557
    protocol: TCP
    targetPort: 5557
#  - port: 8089
#    name: loc-master-web
#    protocol: TCP
#    targetPort: 8089
  selector:
    job-name: locust
status:
  loadBalancer: {}
